// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *uic_time;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_date = NULL;lv_obj_t *ui_temp = NULL;lv_obj_t *ui_hum = NULL;lv_obj_t *ui_press = NULL;lv_obj_t *ui_imagepress = NULL;lv_obj_t *ui_ArcHum = NULL;lv_obj_t *ui_BarTemp = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, -3 );
lv_obj_set_y( ui_time, -97 );
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"time");
lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_date, -2 );
lv_obj_set_y( ui_date, -64 );
lv_obj_set_align( ui_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_date,"date");

ui_temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp, -114 );
lv_obj_set_y( ui_temp, 96 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp,"temp");
lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_hum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hum, -1 );
lv_obj_set_y( ui_hum, 98 );
lv_obj_set_align( ui_hum, LV_ALIGN_CENTER );
lv_label_set_text(ui_hum,"hum");
lv_obj_set_style_text_font(ui_hum, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_press = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_press, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_press, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_press, 113 );
lv_obj_set_y( ui_press, 100 );
lv_obj_set_align( ui_press, LV_ALIGN_CENTER );
lv_label_set_text(ui_press,"press");
lv_obj_set_style_text_font(ui_press, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imagepress = lv_image_create(ui_Screen1);
lv_image_set_src(ui_imagepress, &ui_img_25776339);
lv_obj_set_width( ui_imagepress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imagepress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imagepress, 106 );
lv_obj_set_y( ui_imagepress, 16 );
lv_obj_set_align( ui_imagepress, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imagepress, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_imagepress, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_imagepress,100);

ui_ArcHum = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcHum, 100);
lv_obj_set_height( ui_ArcHum, 100);
lv_obj_set_x( ui_ArcHum, -1 );
lv_obj_set_y( ui_ArcHum, 23 );
lv_obj_set_align( ui_ArcHum, LV_ALIGN_CENTER );
lv_arc_set_value(ui_ArcHum, 50);
lv_obj_set_style_border_color(ui_ArcHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ArcHum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarTemp = lv_bar_create(ui_Screen1);
lv_bar_set_range(ui_BarTemp, 0,40);
lv_bar_set_value(ui_BarTemp,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarTemp, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarTemp, 10);
lv_obj_set_height( ui_BarTemp, 100);
lv_obj_set_x( ui_BarTemp, -114 );
lv_obj_set_y( ui_BarTemp, 9 );
lv_obj_set_align( ui_BarTemp, LV_ALIGN_CENTER );
lv_obj_set_style_border_color(ui_BarTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BarTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BarTemp, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_BarTemp, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_BarTemp, lv_color_hex(0xF81515), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_BarTemp, lv_color_hex(0xEB1111), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_BarTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_BarTemp,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_BarTemp, lv_obj_get_style_pad_right(ui_BarTemp,LV_PART_MAIN) + 1, LV_PART_MAIN );
uic_time = ui_time;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_time= NULL;
ui_time= NULL;
ui_date= NULL;
ui_temp= NULL;
ui_hum= NULL;
ui_press= NULL;
ui_imagepress= NULL;
ui_ArcHum= NULL;
ui_BarTemp= NULL;

}
