// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1486456472);   // assets/vecteezy_thermometer-3d-illustration-isolated_48675674.png
LV_IMG_DECLARE( ui_img_699858216);   // assets/vecteezy_ai-generated-macro-of-fresh-water-droplets_35644659.png
LV_IMG_DECLARE( ui_img_25776339);   // assets/vecteezy_pressure-gauge-with-green-dial-displaying-measurement-and_65916416.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
