// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_date;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_hum;
extern lv_obj_t *ui_press;
extern lv_obj_t *ui_Imagetemp;
extern lv_obj_t *ui_imagehum;
extern lv_obj_t *ui_imagepress;
// CUSTOM VARIABLES
extern lv_obj_t *uic_time;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

