// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_time;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_time = NULL;lv_obj_t *ui_date = NULL;lv_obj_t *ui_temp = NULL;lv_obj_t *ui_hum = NULL;lv_obj_t *ui_press = NULL;lv_obj_t *ui_Imagetemp = NULL;lv_obj_t *ui_imagehum = NULL;lv_obj_t *ui_imagepress = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, -3 );
lv_obj_set_y( ui_time, -97 );
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"time");
lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_date, -2 );
lv_obj_set_y( ui_date, -64 );
lv_obj_set_align( ui_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_date,"date");

ui_temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp, -114 );
lv_obj_set_y( ui_temp, 96 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp,"temp");

ui_hum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_hum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hum, -1 );
lv_obj_set_y( ui_hum, 98 );
lv_obj_set_align( ui_hum, LV_ALIGN_CENTER );
lv_label_set_text(ui_hum,"hum");

ui_press = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_press, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_press, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_press, 113 );
lv_obj_set_y( ui_press, 100 );
lv_obj_set_align( ui_press, LV_ALIGN_CENTER );
lv_label_set_text(ui_press,"press");

ui_Imagetemp = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Imagetemp, &ui_img_642415999);
lv_obj_set_width( ui_Imagetemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Imagetemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Imagetemp, -109 );
lv_obj_set_y( ui_Imagetemp, 14 );
lv_obj_set_align( ui_Imagetemp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imagetemp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Imagetemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Imagetemp,100);

ui_imagehum = lv_image_create(ui_Screen1);
lv_image_set_src(ui_imagehum, &ui_img_699858216);
lv_obj_set_width( ui_imagehum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imagehum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imagehum, -1 );
lv_obj_set_y( ui_imagehum, 16 );
lv_obj_set_align( ui_imagehum, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imagehum, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_imagehum, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_imagehum,100);

ui_imagepress = lv_image_create(ui_Screen1);
lv_image_set_src(ui_imagepress, &ui_img_25776339);
lv_obj_set_width( ui_imagepress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imagepress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imagepress, 106 );
lv_obj_set_y( ui_imagepress, 16 );
lv_obj_set_align( ui_imagepress, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imagepress, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_imagepress, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_imagepress,100);

uic_time = ui_time;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_time= NULL;
ui_time= NULL;
ui_date= NULL;
ui_temp= NULL;
ui_hum= NULL;
ui_press= NULL;
ui_Imagetemp= NULL;
ui_imagehum= NULL;
ui_imagepress= NULL;

}
